-- MySQL Script generated by MySQL Workbench
-- 06/10/14 17:29:27
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema lab_database_schema
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `lab_database_schema` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `lab_database_schema` ;

-- -----------------------------------------------------
-- Table `lab_database_schema`.`rooms`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`rooms` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `room_number` INT UNSIGNED NOT NULL,
  `floor_location` VARCHAR(10) NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`widths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`widths` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `width` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`depths`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`depths` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `depth` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `depth_UNIQUE` (`depth` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`racks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`racks` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `name` VARCHAR(15) NOT NULL,
  `old_name` VARCHAR(15) NULL,
  `room_id` INT UNSIGNED NOT NULL,
  `height_ru` INT UNSIGNED NOT NULL,
  `width_id` INT UNSIGNED NOT NULL,
  `depth_id` INT UNSIGNED NOT NULL,
  `max_power` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `room_id_idx` (`room_id` ASC),
  INDEX `width_id_idx` (`width_id` ASC),
  INDEX `depth_id_idx` (`depth_id` ASC),
  CONSTRAINT `room_id`
    FOREIGN KEY (`room_id`)
    REFERENCES `lab_database_schema`.`rooms` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `width_id`
    FOREIGN KEY (`width_id`)
    REFERENCES `lab_database_schema`.`widths` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `depth_id`
    FOREIGN KEY (`depth_id`)
    REFERENCES `lab_database_schema`.`depths` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '	';


-- -----------------------------------------------------
-- Table `lab_database_schema`.`equipment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`equipment` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `BN_barcode_number` VARCHAR(10) NOT NULL,
  `vendor_id` INT UNSIGNED NOT NULL,
  `model` VARCHAR(10) NOT NULL,
  `serial_num` INT UNSIGNED NOT NULL,
  `GFE_id` VARCHAR(10) NOT NULL,
  `affiliated` CHAR NOT NULL,
  `parent_rack_id` INT UNSIGNED NULL,
  `elevation` INT UNSIGNED NULL COMMENT 'in RU. Only valid if \'located\' field is set to \'rack\'',
  `parent_equipment_id` INT UNSIGNED NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `rack_id_idx` (`parent_rack_id` ASC),
  INDEX `eqipment_id_idx` (`parent_equipment_id` ASC),
  CONSTRAINT `parent_rack_id`
    FOREIGN KEY (`parent_rack_id`)
    REFERENCES `lab_database_schema`.`racks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `parent_eqipment_id`
    FOREIGN KEY (`parent_equipment_id`)
    REFERENCES `lab_database_schema`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`connector_types`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`connector_types` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(10) NOT NULL,
  `type` CHAR NOT NULL,
  `connector_typescol` VARCHAR(45) NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`optical_cassettes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`optical_cassettes` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `rack_id` INT UNSIGNED NOT NULL COMMENT 'foreign key to racks table',
  `elevation` INT UNSIGNED NOT NULL COMMENT 'in RU',
  `slot_count` INT UNSIGNED NOT NULL COMMENT 'slot number of the min cassette chassis',
  `name` VARCHAR(10) NOT NULL,
  `port_count` INT UNSIGNED NOT NULL,
  `connector_id` INT UNSIGNED NOT NULL,
  `MTP_type` INT UNSIGNED NOT NULL COMMENT 'number of strands in the MTP',
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `rack_id_idx` (`rack_id` ASC),
  INDEX `conector_id_idx` (`connector_id` ASC),
  CONSTRAINT `rack_id`
    FOREIGN KEY (`rack_id`)
    REFERENCES `lab_database_schema`.`racks` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `connector_id`
    FOREIGN KEY (`connector_id`)
    REFERENCES `lab_database_schema`.`connector_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`vendors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`vendors` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `vendor` VARCHAR(20) NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`MTP_connects`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`MTP_connects` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `optical_connection_id_1` INT UNSIGNED NOT NULL,
  `optical_connection_id_2` INT UNSIGNED NOT NULL,
  `port_number_1` INT UNSIGNED NOT NULL,
  `port_number_2` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `optical_connection_id_1_idx` (`optical_connection_id_1` ASC),
  INDEX `optical_connection_id_2_idx` (`optical_connection_id_2` ASC),
  CONSTRAINT `optical_connection_id_1`
    FOREIGN KEY (`optical_connection_id_1`)
    REFERENCES `lab_database_schema`.`optical_cassettes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `optical_connection_id_2`
    FOREIGN KEY (`optical_connection_id_2`)
    REFERENCES `lab_database_schema`.`optical_cassettes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`ports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`ports` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `connector_type` CHAR NOT NULL COMMENT 'Represents whether a connector is refrencing something on a piece of equipment or an optical cassette',
  `eqipment_id` INT UNSIGNED NULL,
  `optical_casette_id` INT UNSIGNED NULL,
  `port_number` INT UNSIGNED NOT NULL,
  `name` VARCHAR(15) NULL COMMENT 'Name printed next to port',
  `port_connector_id` INT UNSIGNED NOT NULL,
  `connector_gender` CHAR NOT NULL COMMENT '\"M\" denotes a male connection, \"F\" denotes female',
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `equipment_id_idx` (`eqipment_id` ASC),
  INDEX `connector_id_idx` (`port_connector_id` ASC),
  INDEX `optical_connection_id_idx` (`optical_casette_id` ASC),
  CONSTRAINT `equipment_id`
    FOREIGN KEY (`eqipment_id`)
    REFERENCES `lab_database_schema`.`equipment` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `port_connector_id`
    FOREIGN KEY (`port_connector_id`)
    REFERENCES `lab_database_schema`.`connector_types` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `optical_connection_id`
    FOREIGN KEY (`optical_casette_id`)
    REFERENCES `lab_database_schema`.`optical_cassettes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `lab_database_schema`.`connections`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `lab_database_schema`.`connections` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'primary key',
  `port_id_1` INT UNSIGNED NOT NULL,
  `port_id_2` INT UNSIGNED NOT NULL,
  `comment` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `port_id_1_idx` (`port_id_1` ASC),
  INDEX `port_id_2_idx` (`port_id_2` ASC),
  CONSTRAINT `port_id_1`
    FOREIGN KEY (`port_id_1`)
    REFERENCES `lab_database_schema`.`ports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `port_id_2`
    FOREIGN KEY (`port_id_2`)
    REFERENCES `lab_database_schema`.`ports` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = '			';


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
